# Generated by Django 4.2.7 on 2024-05-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_ad", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_ad", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=128, unique=True)),
                ("phone_number", models.CharField(max_length=16, unique=True)),
                (
                    "student_type",
                    models.CharField(choices=[("Bakalavr", "Bachelor"), ("Magister", "Master")], max_length=64),
                ),
                ("contract", models.IntegerField(default=0)),
                ("separated", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_ad", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentSponsor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_ad", models.DateTimeField(auto_now=True)),
                ("separated", models.IntegerField(default=0)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sponsor", to="sponsor.student"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="student", to="sponsor.student"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="student",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="university", to="sponsor.university"
            ),
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_ad", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=256, unique=True)),
                ("phone_number", models.CharField(max_length=16, unique=True)),
                ("sponsor_sum", models.IntegerField(default=0)),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[("Jismoniy shaxs", "Pysical"), ("Yuridik shaxs", "Legal")], max_length=32
                    ),
                ),
                (
                    "sponsor_condition",
                    models.CharField(
                        choices=[
                            ("Yangi", "New"),
                            ("Modernizatsiyada", "Modernization"),
                            ("Tasdiqlangan", "Check"),
                            ("Bekor qilingan", "Canceled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("transfers", models.CharField(choices=[("Pul o'tkazmalari", "Money Transfers")], max_length=32)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sponsor.organization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
