# Generated by Django 4.2.7 on 2024-05-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="phone_number",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
