# Generated by Django 4.2.7 on 2024-05-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0002_alter_sponsor_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="separated",
            field=models.IntegerField(default=0),
        ),
    ]
