# Generated by Django 4.2.7 on 2024-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0003_sponsor_separated"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="default_sum",
            field=models.CharField(
                choices=[
                    ("1 000 000", "One"),
                    ("5 000 000", "Five"),
                    ("7 000 000", "Seven"),
                    ("10 000 000", "Ten"),
                    ("30 000 000", "Thirty"),
                ],
                default=1,
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
