# Generated by Django 4.2.7 on 2024-05-13 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0005_alter_sponsor_default_sum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="separated",
        ),
    ]
