# Generated by Django 4.2.7 on 2024-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0006_remove_student_separated"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="separated",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
