# Generated by Django 4.2.7 on 2024-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0007_student_separated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="organization",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
