# Generated by Django 4.2.7 on 2024-05-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0009_remove_sponsor_default_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="separated",
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="studentsponsor",
            name="separated",
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
    ]
